"""Tests for how A5 treats the recorded glass noise floor.

Root cause (review 2, 2026-09-29): reports/noise_floors.json is regenerated by
tests/test_reference_data.py::test_pairwise_noise_floors_written from the
C(5,2)=10 frame pairs of ONE simulation per case.  For a glass that is frame
spacing inside a single quench -- smaller than the distance between
INDEPENDENT quenches, and a perfect rebuild is an independent quench -- so the
1.5x gate on that floor could fail even a perfect rebuild.  AGENTS.md (post
Review 2) requires every root cause named in a report to carry a reproducing
test that fails before the fix:

* test_a5_discloses_glass_floor_provenance fails on the pre-fix acceptance
  runner (no floor_note field, no disclosure) and passes after: whenever the
  floor on record carries no provenance note, A5 honestly flags it as
  "glass floor measured within one quench (may be too tight)" in the rows and
  the criterion evidence.
* test_glass_cross_quench_spacing_exceeds_one_quench_floor (slow) measures
  the claim itself: >= 3 independent quenches of the identical protocol, and
  the mean distance between quenches exceeds the within-one-quench spacing
  the recorded floor is built from.
"""
import itertools
import json
import subprocess
import sys

import numpy as np
import pytest

from tools import acceptance as acc

FLOORS = acc.ROOT / "reports" / "noise_floors.json"
GLASS_DIR = acc.ROOT / "bench" / "reference" / "lj_glass"
GENERATOR = acc.ROOT / "bench" / "reference" / "generate_reference.py"
WITHIN_ONE_QUENCH = ("glass floor measured within one quench "
                     "(may be too tight)")


def _read_frames(directory):
    from chaord.io.frames import read_frame
    return [read_frame(directory / f"frame_{k}.npz") for k in range(5)]


def _pair_distances(frames, dialect):
    from chaord.cv.noise import distance, observables
    return [distance(observables(a, dialect), observables(b, dialect))
            for a, b in itertools.combinations(frames, 2)]


def test_a5_discloses_glass_floor_provenance():
    """The glass row and the criterion evidence disclose how the floor was
    measured: the JSON entry's own note when it has one, else the explicit
    within-one-quench caveat (never silence).

    W7 step 8 (2026-10-04): the A5 glass case is ka_glass (Kob-Andersen);
    the monatomic lj_glass is RETIRED from the criterion (a5_excluded, kept
    as the documented cavitated-solid example), so the disclosure is
    asserted on the active glass case."""
    # fit_crystal refuses placeholder species at source (patch A, W7
    # follow-up); no conftest guard is needed
    entry = json.loads(FLOORS.read_text(encoding="utf-8"))["ka_glass"]
    res = acc.check_a5(case_filter="ka_glass")
    row = next(r for r in res["details"]["rows"]
               if r["case"] == "reference/ka_glass")
    expected = entry.get("note") or WITHIN_ONE_QUENCH
    assert row.get("floor_note") == expected
    assert "floor provenance:" in res["evidence"]
    assert expected.split(". ")[0] in res["evidence"]
    # the retired monatomic case must be honestly absent, not silently gone
    prov = json.loads((GLASS_DIR / "provenance.json").read_text("utf-8"))
    assert prov.get("a5_excluded"), (
        "lj_glass has no a5_excluded record; its removal from the A5 rows "
        "would be silent")


# The ka_glass history line as the lifter writes it (scaled counts stated):
# melt 2000 + quench 1.9 K at 0.000475/step (= 4000 steps) + anneal 4000.
KA_HISTORY = ("  history melt 2 for 2000 -> quench to 0.1 at 0.000475 "
              "-> anneal 0.1 for 4000\n")


def test_a5_budget_covers_the_measured_glass_history_rebuild():
    """The A5 rebuild budget must scale with the MD step count the program
    itself states, not N alone.  Reproducing failure (2026-10-04, this
    box): the D7-re-derived ka_glass protocol runs 10,000 MD steps at
    N=2,000; the linear-in-N-only budget gave 300 s while a real draw
    measured 366 s under load (231 s on the sweep-day box), so
    test_a5_discloses_glass_floor_provenance failed with 'rebuild
    exceeded the time budget'.  The budget must clear the worst measured
    draw by >= 1.5x."""
    budget = acc._a5_budget(2000, KA_HISTORY)
    assert budget >= 1.5 * 366, budget


def test_a5_budget_linear_floor_for_non_history_rebuilds():
    """Programs without a history line (packing + short relax) keep the
    documented linear-in-N floor: 150 s base, 150 s per extra 1,000 atoms."""
    assert acc._a5_budget(500) == 150
    assert acc._a5_budget(500, "no history line here") == 150
    assert acc._a5_budget(2000, "no history line here") == 300


@pytest.mark.slow
def test_glass_cross_quench_spacing_exceeds_one_quench_floor(tmp_path):
    """>= 3 independent quenches of the identical melt-quench protocol (the
    checked-in bench/reference/lj_glass quench plus two fresh seeded ones from
    the repo's own generator, which must not and does not import chaord):
    the mean cross-quench distance exceeds the mean within-one-quench spacing
    of the checked-in quench -- i.e. a floor built from one quench's frame
    spacing is tighter than a perfect independent rebuild would sit."""
    from chaord.dialects import load_dialect

    dl = load_dialect(("core", "lj"))
    quenches = {"20260928": _read_frames(GLASS_DIR)}
    for seed in (20261001, 20261002):
        out = tmp_path / f"seed{seed}"
        r = subprocess.run(
            [sys.executable, str(GENERATOR), "--only", "lj_glass",
             "--seed", str(seed), "--out", str(out)],
            capture_output=True, text=True, cwd=acc.ROOT, check=True)
        assert "lj_glass" in r.stdout
        quenches[str(seed)] = _read_frames(out / "lj_glass")
    assert len(quenches) >= 3

    from chaord.cv.noise import distance, observables
    within = _pair_distances(quenches["20260928"], dl)
    within_mean = {k: float(np.mean([d[k] for d in within]))
                   for k in within[0]}
    cross = []
    for qa, qb in itertools.combinations(sorted(quenches), 2):
        for fa in quenches[qa]:
            for fb in quenches[qb]:
                cross.append(distance(observables(fa, dl),
                                      observables(fb, dl)))
    cross_mean = {k: float(np.mean([d[k] for d in cross])) for k in cross[0]}
    assert cross_mean["gr_rms"] > within_mean["gr_rms"], (
        f"cross-quench gr_rms {cross_mean['gr_rms']:.4f} not above the "
        f"within-one-quench mean {within_mean['gr_rms']:.4f}: a one-quench "
        "floor would not be too tight and the A5 caveat would be wrong")
    assert cross_mean["cn_tv"] > within_mean["cn_tv"], (
        f"cross-quench cn_tv {cross_mean['cn_tv']:.4f} not above the "
        f"within-one-quench mean {within_mean['cn_tv']:.4f}")
