import numpy as np, time
from decompile import decompile, to_text
from compile_prog import compile_program
rng = np.random.default_rng(3)
t = time.time()
o = np.load('snap.npz'); P = decompile(o['r'], o['L'], 0.65)
later = np.load('snap_later.npz'); P2 = decompile(later['r'], later['L'], 0.65)
rA, LA = compile_program(P, rng, physics=False); PA = decompile(rA, LA, 0.65)
rB, LB = compile_program(P, rng, physics=True);  PB = decompile(rB, LB, 0.65)
print(f"(round trip took {time.time()-t:.0f}s)\n")
def row(name, f):
    return f"{name:<34}" + "".join(f"{f(x):>16}" for x in (P, P2, PA, PB))
m = lambda Q: (Q['rm'] > 0.8)
print(f"{'':<34}{'original':>16}{'same run later':>16}{'build only':>16}{'build + MD':>16}")
print("-- stated in the program")
print(row("atoms", lambda Q: f"{Q['N']}"))
print(row("net vacancies", lambda Q: f"{sum(c['net'] for c in Q['defects'])}"))
print(row("lattice a / strain zz", lambda Q: f"{Q['a_x']:.3f} / {100*(Q['a_z']/Q['a_x']-1):+.1f}%"))
print(row("liquid density", lambda Q: f"{Q['rho']:.3f}"))
print("-- NOT stated (held out): emerge or not")
print(row("coordination number", lambda Q: f"{Q['cn']:.1f} +- {Q['cn_sd']:.1f}"))
print(row("g(r) first peak (pos, height)", lambda Q: f"{Q['pk_r']:.2f}, {Q['pk_h']:.2f}"))
print(row("g(r) distance to original (RMS)", lambda Q: f"{np.sqrt(np.mean((Q['gr'][m(Q)]-P['gr'][m(P)])**2)):.3f}"))
print(row("bond-angle distr. distance (TV)", lambda Q: f"{0.5*np.abs(Q['bad']-P['bad']).sum():.3f}"))
print(row("liquid local order <q6>", lambda Q: f"{Q['q6l']:.3f}"))
print(row("interface widths", lambda Q: f"{Q['w_up']:.1f}, {Q['w_lo']:.1f}"))
print(row("defects found", lambda Q: "/".join(c['name'][:4] for c in Q['defects']) or "-"))
print("\n=== program decompiled from the 'build + MD' output ===")
print(to_text(PB))
